#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean solvers
wclean applications/solvers/pythonLaplacianFoam
wclean applications/solvers/pythonSolids4Foam

# Clean libraries
wclean src/pythonLinearElastic
wclean src/pythonVelocity

# Clean tutorials
(cd tutorials && ./Allclean)

#------------------------------------------------------------------------------
