#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions



# Create mesh
runApplication blockMesh

# Run solver
runApplication pythonSolids4Foam

# ----------------------------------------------------------------- end-of-file

