#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


cleanCase
\rm -f constant/polyMesh/boundary case.foam
\rm -rf system/*Subset constant/*Subset history

# Compatibility changes for foam extend
if [[ $WM_PROJECT = "foam" ]]
    then
        sed -i 's\symmetryPlane;\symmetry;\g' "0/D"
        sed -i 's\symmetryPlane\symmetry\g' "system/blockMeshDict"
fi

#Remove blockMeshDict in constant/polyMesh for foam-extend  
rm -r constant/polyMesh