#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Revert compatibility changes for foam extend
if [[ $WM_PROJECT = "foam" ]]
then
    # Remove blockMeshDict from constant/polyMesh
    rm -rf constant/polyMesh
fi

cleanCase
