#!/bin/bash

# Usage
# Pass the argument 'parallel' to run the case in parallel, e.g.
# $> ./Allrun parallel

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

if [[ "$1" == "parallel" ]]; then
    # Decompose the case
    runApplication decomposePar

    # Run solver in serial
    runParallel pythonIcoFoam

    # Reconstruct the case
    runApplication reconstructPar
else
    # Run solver in serial
    runApplication pythonIcoFoam
fi

# Extract components of U
runApplication -s componentsU postProcess -func "components(U)" -latestTime

if [[ $WM_PROJECT_VERSION = "v2012" ]]; then
    echo "Printing with singleGraph"
    runApplication -s singleGraph postProcess -func singleGraph -latestTime

    # Generate plot using gnuplot
    runApplication gnuplot plotSingleGraph.gnuplot

elif [[ $WM_PROJECT_VERSION = "9" ]]; then
    echo "Printing with graphUniform"
    runApplication -s graphUniform postProcess -func graphUniform -latestTime
    
    # Generate plot using gnuplot
    runApplication gnuplot plotGraphUniform.gnuplot
fi

echo "See plot.pdf"
