#!/bin/bash

# Usage
# Pass the argument 'parallel' to run the case in parallel, e.g.
# $> ./Allrun parallel

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

if [[ "$1" == "parallel" ]]; then
    # Decompose the case
    runApplication decomposePar

    # Run solver in serial
    runParallel pythonIcoFoam

    # Reconstruct the case
    runApplication reconstructPar
else
    # Run solver in serial
    runApplication pythonIcoFoam
fi

# Extract components of U
runApplication -s componentsU postProcess -func "components(U)" -latestTime

# Extract plot of Ux along the top patch
runApplication -s graphUniform postProcess -func graphUniform -latestTime

# Generate plot using gnuplot
runApplication gnuplot plot.gnuplot
echo "See plot.pdf"
