#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

if [ $WM_PROJECT_VERSION = "v2012" ]; then
    echo "HEEEEREEE"
    keepCases="plateHole pythonCavity pythonHotBlock"

    for caseName in $keepCases
    do
        ( cd $caseName && foamCleanTutorials )
    done


else 
    dir=${PWD##*/}

    echo "--------"
    echo "Cleaning ${dir}s ..."
    echo "Removing backup files"

    foamCleanTutorials cases

    echo "--------"
fi


#------------------------------------------------------------------------------
