#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
runApplication blockMesh

# Expose  GPU
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/simon/anaconda3/envs/pybind-gpu/lib

# Run solver
runApplication pythonSolids4Foam
# ----------------------------------------------------------------- end-of-file

