#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Run solver
runApplication icoFoam

# Extract components of U
runApplication -s U postProcess -func "components(U)" -latestTime

# Extract plot of Ux along the top patch
#runApplication -s singleGraph postProcess -func singleGraph -latestTime
echo "Extracting Ux from movingWall to movingWall.Ux.txt"
head -453 0.5/Ux | tail -120 > movingWall.Ux.txt

# Generate plot using gnuplot
runApplication gnuplot plot.gnuplot
echo "See plot.pdf"
