#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
runApplication blockMesh

# Run solver
#runApplication pythonSolids4Foam
echo "Solver not run as this case is very slow!"
echo "You can run this case by uncommenting the run solver line in the Allrun script"

# ----------------------------------------------------------------- end-of-file

