#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Run solver
runApplication pythonLaplacianbyCopyFoam

# Sample along vertical line
runApplication postProcess -func singleGraph -latestTime

# Generate plot using gnuplot
runApplication gnuplot plot.gnuplot
echo "See plot.pdf"
