#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
runApplication blockMesh

# Run decomposePar
decomposePar

# Run solver
# runApplication pythonSolids4Foam
mpirun -np 4 icoFoam -parallel

# Run reconstructPar
reconstructPar

# Extract components of U
runApplication -s componentsU postProcess -func "components(U)" -latestTime

# Extract plot of Ux along the top patch
runApplication -s singleGraph postProcess -func singleGraph -latestTime

# Generate plot using gnuplot
runApplication gnuplot plot.gnuplot
echo "See plot.pdf"

# ----------------------------------------------------------------- end-of-file

