#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create mesh
runApplication blockMesh

# Run decomposePar
decomposePar

# Run solver
# runApplication pythonSolids4Foam
mpirun -np 4 pythonSolids4Foam -parallel

# Run reconstructPar
reconstructPar
# ----------------------------------------------------------------- end-of-file

