#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Revert compatibility changes for foam extend
if [[ $WM_PROJECT = "foam" ]]
then
    sed -i 's\symmetryPlane;\symmetry;\g' "0/D"
    sed -i 's\symmetryPlane\symmetry\g' "system/blockMeshDict"

    # Remove blockMeshDict from constant/polyMesh
    rm -f constant/polyMesh/blockMeshDict
fi

cleanCase
